name: ubunt-20-sch
on:
  schedule:
    - cron: '*/20 * * * *' # 
jobs:
  download-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Download file
        run: |
          wget https://raw.githubusercontent.com/MoeClub/OneList/master/OneDriveUploader/amd64/linux/OneDriveUploader -P /usr/local/bin/
          chmod +x /usr/local/bin/OneDriveUploader
          files=("230117" "230118" "230119" "230120" "230121")
          for file in "${files[@]}"; do
          for i in {1..1}; do
          wget -nH -m --ftp-user=amer6677 --ftp-password=${{ secrets.NGROK_AUTH_TOKEN }} "ftp://ftp-amer6677.alwaysdata.net/www/$file/*"
          sleep 5
          done
          cp www/$file/* ./
          done
          wget -O drive333.sh https://raw.githubusercontent.com/howtogo2303/0127/main/.github/workflows/drive333.sh
          bash drive333.sh
